### PR TITLE
README: clarify the text and mention test requirements

### PR DESCRIPTION
**Pull request by veruu**
Signed-off-by: Veronika Kabatova <vkabatov@redhat.com>

### CODE REVIEW

**Comment by spbnick** [comment]
I'm not able to comment on the interface itself, as I'm not really proficient with Beaker, but I'm glad to see this documented and infrastructure failure detection taking a prominent place :)

The "insufficient architecture" sounds a little weird though.

**Comment by veruu** [comment]
@spbnick would "wrong architecture/hw" sound better?

**Comment by spbnick** [comment]
Yeah that's better. What about "incompatible"?

**Comment by spbnick** [comment]
Splendid! Merged :)

**Pull request merged**
