### PR TITLE
RHELPLAN-7263 : Init smart testing tool

### PR DESCRIPTION
**Pull request by idorax**
Rachel, I'd like to save the initial version of the smart testing tool before we develop next version, please take a look, thanks!

### CODE REVIEW

**Comment by rasibley** [comment]
@idorax I would instead go one level higher and create a new repo in https://github.com/RH-FMK, @veruu or @spbnick what do you think ?

**Comment by spbnick** [comment]
@rasibley, yes, and no need to put everything into a subdirectory then.

**Comment by rasibley** [comment]
@spbnick thanks! does @idorax have permission to create a new repo?

**Comment by spbnick** [comment]
@rasibley, I just invited @idorax to the project and when he accepts the invitation he should receive the permissions to create a repo.

**Comment by idorax** [comment]
@rasibley , @spbnick , I'd like to close this PR as we will save the code to kpet repo.

**Pull request closed without merging**
